var goog=goog||{};goog.global=this;goog.DEBUG=!0;goog.LOCALE="en";goog.evalWorksForGlobals_=null;goog.provide=function(a){goog.exportPath_(a)};goog.isProvided_=function(a){return!goog.implicitNamespaces_[a]&&!!goog.getObjectByName(a)};goog.setTestOnly=function(a){if(!goog.DEBUG)throw a=a||"",Error("Importing test-only code into non-debug environment"+a?": "+a:".");};
goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(goog.isDefAndNotNull(d[e]))d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};goog.addDependency=function(){};goog.useStrictRequires=!1;
goog.require=function(){};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a){return a};goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.getInstance=function(){return a.instance_||(a.instance_=new a)}};
goog.typeOf=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b};goog.propertyIsEnumerableCustom_=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return!0;return!1};goog.propertyIsEnumerable_=function(a,b){return a instanceof Object?Object.prototype.propertyIsEnumerable.call(a,b):goog.propertyIsEnumerableCustom_(a,b)};goog.isDef=function(a){return a!==void 0};goog.isNull=function(a){return a===null};goog.isDefAndNotNull=function(a){return a!=null};
goog.isArray=function(a){return goog.typeOf(a)=="array"};goog.isArrayLike=function(a){var b=goog.typeOf(a);return b=="array"||b=="object"&&typeof a.length=="number"};goog.isDateLike=function(a){return goog.isObject(a)&&typeof a.getFullYear=="function"};goog.isString=function(a){return typeof a=="string"};goog.isBoolean=function(a){return typeof a=="boolean"};goog.isNumber=function(a){return typeof a=="number"};goog.isFunction=function(a){return goog.typeOf(a)=="function"};
goog.isObject=function(a){a=goog.typeOf(a);return a=="object"||a=="array"||a=="function"};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};goog.UID_PROPERTY_="closure_uid_"+Math.floor(Math.random()*2147483648).toString(36);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;
goog.cloneObject=function(a){var b=goog.typeOf(a);if(b=="object"||b=="array"){if(a.clone)return a.clone();var b=b=="array"?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b){var c=b||goog.global;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,d);return a.apply(c,b)}}else return function(){return a.apply(c,arguments)}};goog.bind=function(){goog.bind=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?goog.bindNative_:goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a){var b=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,b);return a.apply(this,c)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval){if(goog.evalWorksForGlobals_==null)goog.global.eval("var _et_ = 1;"),typeof goog.global._et_!="undefined"?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1;if(goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}}else throw Error("goog.globalEval not available");};goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){for(var a=a.split("-"),b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?goog.cssNameMappingStyle_=="BY_WHOLE"?c:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
goog.getMsg=function(a,b){var c=b||{},d;for(d in c)var e=(""+c[d]).replace(/\$/g,"$$$$"),a=a.replace(RegExp("\\{\\$"+d+"\\}","gi"),e);return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a};
goog.base=function(a,b){var c=arguments.callee.caller;if(c.superClass_)return c.superClass_.constructor.apply(a,Array.prototype.slice.call(arguments,1));for(var d=Array.prototype.slice.call(arguments,2),e=!1,f=a.constructor;f;f=f.superClass_&&f.superClass_.constructor)if(f.prototype[b]===c)e=!0;else if(e)return f.prototype[b].apply(a,d);if(a[b]===c)return a.constructor.prototype[b].apply(a,d);else throw Error("goog.base called from a method of one name to a method of a different name");};
goog.scope=function(a){a.call(goog.global)};goog.MODIFY_FUNCTION_PROTOTYPES=!0;
if(goog.MODIFY_FUNCTION_PROTOTYPES)Function.prototype.bind=Function.prototype.bind||function(a){if(arguments.length>1){var b=Array.prototype.slice.call(arguments,1);b.unshift(this,a);return goog.bind.apply(null,b)}else return goog.bind(this,a)},Function.prototype.partial=function(){var a=Array.prototype.slice.call(arguments);a.unshift(this,null);return goog.bind.apply(null,a)},Function.prototype.inherits=function(a){goog.inherits(this,a)},Function.prototype.mixin=function(a){goog.mixin(this.prototype,
a)};var cvox={BuildDefs:{}};cvox.BuildConfig={};cvox.AriaUtil=function(){};cvox.AriaUtil.MIN="Min ";cvox.AriaUtil.MAX="Max ";
cvox.AriaUtil.WIDGET_ROLE_TO_NAME={alert:"Alert",alertdialog:"Alert dialog",button:"Button",checkbox:"Check box",combobox:"Combo box",dialog:"Dialog",gridcell:"Grid cell",link:"Link",log:"Log",marquee:"Marquee",menuitem:"Menu item",menuitemcheckbox:"Menu item check box",menuitemradio:"Menu item radio button",option:"Option",progressbar:"Progress bar",radio:"Radio button",radiogroup:"Radio button group",scrollbar:"Scroll bar",slider:"Slider",spinbutton:"Spin button",status:"Status",tab:"Tab",tabpanel:"Tab panel",
textbox:"Text box",timer:"Timer",toolbar:"Tool bar",tooltip:"Tool tip",treeitem:"Tree item"};cvox.AriaUtil.STRUCTURE_ROLE_TO_NAME={article:"Article",columnheader:"Column header",definition:"Definition",directory:"Directory",document:"Document",group:"Group",heading:"Heading",img:"Image",list:"List",listitem:"List item",math:"Math",note:"Note",region:"Region",row:"Row",rowheader:"Row header",separator:"Separator"};
cvox.AriaUtil.ATTRIBUTE_VALUE_TO_STATUS=[{name:"aria-autocomplete",values:{inline:"Autocompletion inline",list:"Autocompletion list",both:"Autocompletion inline and list"}},{name:"aria-checked",values:{"true":"Checked","false":"Not checked",mixed:"Partially checked"}},{name:"aria-disabled",values:{"true":"Disabled"}},{name:"aria-expanded",values:{"true":"Expanded","false":"Collapsed"}},{name:"aria-haspopup",values:{"true":"Has pop up"}},{name:"aria-invalid",values:{"true":"Invalid input",grammar:"Grammatical mistake detected",
spelling:"Spelling mistake detected"}},{name:"aria-multiline",values:{"true":"Multi line"}},{name:"aria-multiselectable",values:{"true":"Multi select"}},{name:"aria-pressed",values:{"true":"Pressed","false":"Not pressed",mixed:"Partially pressed"}},{name:"aria-readonly",values:{"true":"Read only"}},{name:"aria-required",values:{"true":"Required"}},{name:"aria-selected",values:{"true":"Selected","false":"Not selected"}}];
cvox.AriaUtil.isHidden=function(a){for(;a;){if(a.getAttribute){if(a.getAttribute("role")=="presentation")return!0;if(a.getAttribute("aria-hidden")=="true")return!0}a=a.parentNode}return!1};cvox.AriaUtil.getRoleName=function(a){var b;a&&a.getAttribute&&(a=a.getAttribute("role"),(b=cvox.AriaUtil.WIDGET_ROLE_TO_NAME[a])||(b=cvox.AriaUtil.STRUCTURE_ROLE_TO_NAME[a]));b||(b="");return b};
cvox.AriaUtil.getState=function(a){var b="";if(a&&a.getAttribute){for(var c=0,d;d=cvox.AriaUtil.ATTRIBUTE_VALUE_TO_STATUS[c];c++){var e=a.getAttribute(d.name);(d=d.values[e])&&(b=b+" "+d)}a.getAttribute("aria-valuetext")?b=b+" "+a.getAttribute("aria-valuetext"):a.getAttribute("aria-valuenow")&&(b=b+" "+a.getAttribute("aria-valuenow"));a.getAttribute("aria-valuemin")&&(b=b+" "+cvox.AriaUtil.MIN+a.getAttribute("aria-valuemin"));a.getAttribute("aria-valuemax")&&(b=b+" "+cvox.AriaUtil.MAX+a.getAttribute("aria-valuemax"))}return b};
cvox.AriaUtil.isControlWidget=function(a){if(a&&a.getAttribute)switch(a=a.getAttribute("role"),a){case "button":case "checkbox":case "combobox":case "menuitemcheckbox":case "menuitemradio":case "radio":case "slider":case "spinbutton":case "textbox":return!0}return!1};cvox.AriaUtil.getLiveRegionValue=function(a){if(!a.hasAttribute)return null;var b=a.getAttribute("aria-live");if(b)return b;a=a.getAttribute("role");switch(a){case "alert":return"assertive";case "log":case "status":return"polite";default:return null}};
cvox.AriaUtil.getLiveRegions=function(a){var b=[];if(a.querySelectorAll){var c=a.querySelectorAll('[role="alert"], [role="log"],  [role="marquee"], [role="status"], [role="timer"],  [aria-live]');if(c)for(var d=0;d<c.length;d++)b.push(c[d])}for(;a;){if(cvox.AriaUtil.getLiveRegionValue(a)){b.push(a);break}a=a.parentElement}return b};if(!cvox.ChromeVoxJSON)cvox.ChromeVoxJSON={};
JSON.toString()=="[object JSON]"?cvox.ChromeVoxJSON=JSON:function(){function a(a){return a<10?"0"+a:a}function b(a){e.lastIndex=0;return e.test(a)?'"'+a.replace(e,function(a){var b=j[a];return typeof b==="string"?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,d){var e,l,m,j,q=f,k,h=d[a];h&&typeof h==="object"&&typeof h.toJSON==="function"&&(h=h.toJSON(a));typeof i==="function"&&(h=i.call(d,a,h));switch(typeof h){case "string":return b(h);case "number":return isFinite(h)?
String(h):"null";case "boolean":case "null":return String(h);case "object":if(!h)return"null";f+=g;k=[];if(Object.prototype.toString.apply(h)==="[object Array]"){j=h.length;for(e=0;e<j;e+=1)k[e]=c(e,h)||"null";m=k.length===0?"[]":f?"[\n"+f+k.join(",\n"+f)+"\n"+q+"]":"["+k.join(",")+"]";f=q;return m}if(i&&typeof i==="object"){j=i.length;for(e=0;e<j;e+=1)l=i[e],typeof l==="string"&&(m=c(l,h))&&k.push(b(l)+(f?": ":":")+m)}else for(l in h)Object.hasOwnProperty.call(h,l)&&(m=c(l,h))&&k.push(b(l)+(f?": ":
":")+m);m=k.length===0?"{}":f?"{\n"+f+k.join(",\n"+f)+"\n"+q+"}":"{"+k.join(",")+"}";f=q;return m}}if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":"null"},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var d=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
e=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,f,g,j={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},i;if(typeof cvox.ChromeVoxJSON.stringify!=="function")cvox.ChromeVoxJSON.stringify=function(a,b,d){var e;g=f="";if(typeof d==="number")for(e=0;e<d;e+=1)g+=" ";else typeof d==="string"&&(g=d);if((i=b)&&typeof b!=="function"&&(typeof b!=="object"||typeof b.length!=="number"))throw Error("JSON.stringify");
return c("",{"":a})};if(typeof cvox.ChromeVoxJSON.parse!=="function")cvox.ChromeVoxJSON.parse=function(a,b){function c(a,d){var e,f,g=a[d];if(g&&typeof g==="object")for(e in g)Object.hasOwnProperty.call(g,e)&&(f=c(g,e),f!==void 0?g[e]=f:delete g[e]);return b.call(a,d,g)}var e,a=String(a);d.lastIndex=0;d.test(a)&&(a=a.replace(d,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),typeof b==="function"?c({"":e},""):e;throw new SyntaxError("JSON.parse");}}();cvox.ExtensionBridge=function(){};cvox.ExtensionBridge.init=function(){var a=cvox.ExtensionBridge;a.listeners=[];try{chrome&&chrome.windows&&window.location.toString().indexOf("chrome-extension://")==0&&window.location.toString().indexOf("background.html")>0?(a.json=JSON,a.context=a.BACKGROUND,a.initBackground()):(a.json=cvox.ChromeVoxJSON,a.context=a.PAGE,a.initPage());return}catch(b){}if(chrome&&chrome.extension)a.json=JSON,a.context=a.CONTENT_SCRIPT,a.initContentScript()};
cvox.ExtensionBridge.BACKGROUND=0;cvox.ExtensionBridge.CONTENT_SCRIPT=1;cvox.ExtensionBridge.PAGE=2;cvox.ExtensionBridge.PORT_NAME="cvox.ExtensionBridge.Port";cvox.ExtensionBridge.PORT_SETUP_MSG="cvox.ExtensionBridge.PortSetup";cvox.ExtensionBridge.send=function(a){var b=cvox.ExtensionBridge;switch(b.context){case b.BACKGROUND:b.sendBackgroundToContentScript(a);break;case b.CONTENT_SCRIPT:b.sendContentScriptToBackground(a);break;case b.PAGE:b.sendPageToContentScript(a)}};
cvox.ExtensionBridge.addMessageListener=function(a){cvox.ExtensionBridge.listeners.push(a)};cvox.ExtensionBridge.initBackground=function(){var a=cvox.ExtensionBridge,b=function(b){b.name==a.PORT_NAME&&b.onMessage.addListener(function(d){for(var e=0;e<a.listeners.length;e++)a.listeners[e](d,b)})};chrome.extension.onConnect.addListener(b);chrome.extension.onConnectExternal.addListener(b)};
cvox.ExtensionBridge.initContentScript=function(){var a=cvox.ExtensionBridge,b=function(b,d,e){for(d=0;d<a.listeners.length;d++)a.listeners[d](b,a.backgroundPort);a.port&&a.port.postMessage(a.json.stringify(b));e({})};chrome.extension.onRequest.addListener(b);window.addEventListener("message",function(b){if(b.data==a.PORT_SETUP_MSG)cvox.ExtensionBridge.setupBackgroundPort(),a.port=b.ports[0],a.port.onmessage=function(b){a.backgroundPort.postMessage(a.json.parse(b.data))}},!1)};
cvox.ExtensionBridge.setupBackgroundPort=function(){var a=cvox.ExtensionBridge;a.backgroundPort=window.location.toString().indexOf("chrome-extension://")==0&&window.location.toString().indexOf("CHROMEVOX_ID")==-1?chrome.extension.connect("CHROMEVOX_ID",{name:a.PORT_NAME}):chrome.extension.connect({name:a.PORT_NAME});a.backgroundPort.onMessage.addListener(function(b){for(var c=0;c<a.listeners.length;c++)a.listeners[c](b,a.backgroundPort);a.port&&a.port.postMessage(a.json.stringify(b))})};
cvox.ExtensionBridge.initPage=function(){var a=cvox.ExtensionBridge;a.channel=new MessageChannel;window.postMessage.apply(window,[a.PORT_SETUP_MSG,[a.channel.port2],"*"]);a.channel.port1.onmessage=function(b){for(var c=0;c<a.listeners.length;c++)a.listeners[c](a.json.parse(b.data),a.channel.port1)}};cvox.ExtensionBridge.sendContentScriptToBackground=function(a){cvox.ExtensionBridge.backgroundPort.postMessage(a)};
cvox.ExtensionBridge.sendBackgroundToContentScript=function(a){chrome.tabs.getSelected(null,function(b){chrome.tabs.sendRequest(b.id,a,function(){})})};cvox.ExtensionBridge.sendPageToContentScript=function(a){cvox.ExtensionBridge.channel.port1.postMessage(cvox.ExtensionBridge.json.stringify(a))};cvox.ExtensionBridge.init();cvox.Interframe=function(){};cvox.Interframe.IF_MSG_PREFIX="cvox.INTERFRAME:";cvox.Interframe.SET_ID="cvox.INTERFRAME_SET_ID";cvox.Interframe.listeners=[];
cvox.Interframe.init=function(){cvox.Interframe.messageListener=function(a){if(a.data.indexOf(cvox.Interframe.IF_MSG_PREFIX)==0){a=a.data.substr(cvox.Interframe.IF_MSG_PREFIX.length);a=cvox.ChromeVoxJSON.parse(a,null);if(a.command==cvox.Interframe.SET_ID)cvox.Interframe.id=a.id;for(var b=0,c;c=cvox.Interframe.listeners[b];b++)c(a)}return!1};window.addEventListener("message",cvox.Interframe.messageListener,!0)};
cvox.Interframe.shutdown=function(){window.removeEventListener("message",cvox.Interframe.messageListener,!0)};cvox.Interframe.addListener=function(a){cvox.Interframe.listeners.push(a)};cvox.Interframe.sendMessageToWindow=function(a,b){var c=cvox.Interframe.IF_MSG_PREFIX+cvox.ChromeVoxJSON.stringify(a,null,null);b.postMessage(c,"*")};
cvox.Interframe.sendMessageToIFrame=function(a,b){if(b.contentWindow)cvox.Interframe.sendMessageToWindow(a,b.contentWindow);else{var c=cvox.Interframe.IF_MSG_PREFIX+cvox.ChromeVoxJSON.stringify(a,null,null),d=document.createElement("script");d.type="text/javascript";if(b.hasAttribute("id")&&document.getElementById(b.id)==b)d.innerHTML="document.getElementById(decodeURI('"+encodeURI(b.id)+"')).contentWindow.postMessage(decodeURI('"+encodeURI(c)+"'), '*');";else{var e="cvox_iframe"+a.id;b.className===
""?b.className=e:b.className.indexOf(e)==-1&&(b.className+=" "+e);d.innerHTML="document.getElementsByClassName(decodeURI('"+encodeURI(e)+"'))[0].contentWindow.postMessage(decodeURI('"+encodeURI(c)+"'), '*');"}document.head.appendChild(d);window.setTimeout(function(){document.head.removeChild(d)},1E3)}};
cvox.Interframe.sendMessageToParentWindow=function(a){if(window.parent!=window)a.sourceId=cvox.Interframe.id,window.parent&&cvox.Interframe.sendMessageToWindow(a,window.parent),a=cvox.Interframe.IF_MSG_PREFIX+cvox.ChromeVoxJSON.stringify(a,null,null),window.location.href="javascript:window.parent.postMessage('"+encodeURI(a)+"', '*');"};cvox.Interframe.sendIdToIFrame=function(a,b){var c={command:cvox.Interframe.SET_ID,id:a};cvox.Interframe.sendMessageToIFrame(c,b)};cvox.Interframe.init();cvox.XpathUtil=function(){};cvox.XpathUtil.evalXPath=function(a,b){try{var c=b.ownerDocument.evaluate(a,b,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null)}catch(d){return[]}for(var e=[],f=c.iterateNext();f;f=c.iterateNext())e.push(f);return e};cvox.XpathUtil.getLeafNodes=function(a){try{var b=a.ownerDocument.evaluate(".//*[count(*)=0]",a,null,XPathResult.ORDERED_NODE_ITERATOR_TYPE,null)}catch(c){return[]}for(var a=[],d=b.iterateNext();d;d=b.iterateNext())a.push(d);return a};
cvox.XpathUtil.xpathSupported=function(){if(typeof XPathResult=="undefined")return!1;return!0};cvox.DomUtil=function(){};
cvox.DomUtil.INPUT_TYPE_TO_INFORMATION_TABLE={button:"Button",checkbox:"Check box",color:"Color picker",datetime:"Date time control","datetime-local":"Date time control",date:"Date control",email:"Edit text for email",file:"File selection",hidden:"",image:"Button",month:"Month control",number:"Edit text numeric only",password:"Password edit text",radio:"Radio button",range:"Slider",reset:"Reset",search:"Edit text for search",submit:"Button",tel:"Edit text for telephone number",text:"Edit text",url:"Edit text for URL",
week:"Week of the year control"};cvox.DomUtil.TAG_TO_INFORMATION_TABLE={A:"Link",H1:"Heading 1",H2:"Heading 2",H3:"Heading 3",H4:"Heading 4",H5:"Heading 5",H6:"Heading 6",BUTTON:"Button",SELECT:"Combo box",TABLE:"Table",TEXTAREA:"Text area"};cvox.DomUtil.isInvisibleStyle=function(a){if(!a)return!1;if(a.display=="none")return!0;if(a.visibility=="hidden")return!0;if(a.opacity==0)return!0;return!1};
cvox.DomUtil.isLeafNode=function(a){if(a.nodeType==1){var b=document.defaultView.getComputedStyle(a,null);if(cvox.DomUtil.isInvisibleStyle(b))return!0}if(cvox.AriaUtil.isHidden(a))return!0;if(a.tagName){if(a.tagName=="OBJECT")return!0;if(a.tagName=="EMBED")return!0;if(a.tagName=="VIDEO")return!0;if(a.tagName=="AUDIO")return!0;if(a.tagName=="IFRAME")return!0;if(a.tagName=="FRAME")return!0}if(cvox.DomUtil.isControl(a))return!0;if(!a.firstChild)return!0;return!1};
cvox.DomUtil.isDescendantOf=function(a,b,c){for(;a;){if(b&&c&&a.tagName&&a.tagName==b&&a.className&&a.className==c)return!0;else if(b&&!c&&a.tagName&&a.tagName==b)return!0;else if(!b&&c&&a.className&&a.className==c)return!0;a=a.parentNode}return!1};cvox.DomUtil.isDescendantOfNode=function(a,b){for(;a&&b;){if(a.isSameNode(b))return!0;a=a.parentNode}return!1};
cvox.DomUtil.getLabel=function(a,b){var c="";if(!a)return"";if(a.hasAttribute&&a.hasAttribute("aria-labelledby"))for(var d=a.getAttribute("aria-labelledby").split(" "),e,f=0;e=d[f];f++)e=document.getElementById(e),c+=cvox.DomUtil.getText(e)+" ";else a.hasAttribute&&a.hasAttribute("aria-label")?c+=a.getAttribute("aria-label"):a&&a.id&&(f=cvox.XpathUtil.evalXPath('//label[@for="'+a.id+'"]',document.body),f.length>0&&(c+=cvox.DomUtil.getText(f[0])+" "));if(c.length<1&&cvox.DomUtil.isControl(a)){for(f=
a;f&&f.tagName!="LABEL";)f=f.parentElement;f&&!f.hasAttribute("for")&&(c+=cvox.DomUtil.getText(f,!0)+" ")}if(c.length<1&&a.hasAttribute&&a.getAttribute("role")=="button")for(f=0;d=a.childNodes[f];f++)e=window.getComputedStyle(d,null),!cvox.DomUtil.isInvisibleStyle(e)&&!cvox.AriaUtil.isHidden(a)&&(c+=" "+cvox.DomUtil.getText(d));if(b&&c.length<1){f=cvox.DomUtil.previousLeafNode(a);for(d=0;f&&(!cvox.DomUtil.hasContent(f)||cvox.DomUtil.isControl(f));)f=cvox.DomUtil.previousLeafNode(f),d++;d=cvox.DomUtil.nextLeafNode(a);
for(e=0;d&&(!cvox.DomUtil.hasContent(d)||cvox.DomUtil.isControl(d));)d=cvox.DomUtil.nextLeafNode(d),e++;if(f&&d){e=a;for(var g=0;e;){if(cvox.DomUtil.isDescendantOfNode(f,e))break;e=e.parentNode;g++}e=a;for(var j=0;e;){if(cvox.DomUtil.isDescendantOfNode(d,e))break;e=e.parentNode;j++}f=j<g?d:f}else f=f||d;f&&(c+=cvox.DomUtil.getText(f)+" ")}return c};
cvox.DomUtil.getTitle=function(a){if(a.constructor==Text)return a.data;else if(a.constructor==HTMLImageElement)return cvox.DomUtil.getImageTitle(a);else if(a.hasAttribute&&a.hasAttribute("title"))return a.getAttribute("title");else if(a.constructor==HTMLInputElement)if(a.type=="image")return cvox.DomUtil.getImageTitle(a);else if(a.type=="submit")return a.hasAttribute&&a.hasAttribute("value")?a.getAttribute("value"):"Submit";else{if(a.type=="reset")return a.hasAttribute&&a.hasAttribute("value")?a.getAttribute("value"):
"Reset"}else if(a.constructor==HTMLButtonElement){for(var b="",c=0,d;d=a.childNodes[c];c++)b+=cvox.DomUtil.getText(d)+" ";return b}return""};
cvox.DomUtil.getValue=function(a){if(a.constructor==HTMLSelectElement)return a.selectedIndex>=0&&a.selectedIndex<a.options.length?a.options[a.selectedIndex].text+"":"";if(a.constructor==HTMLTextAreaElement)return a.value;if(a.constructor==HTMLInputElement)switch(a.type){case "hidden":case "image":case "submit":case "reset":case "checkbox":case "radio":break;case "password":return a.value.replace(/./g,"*");default:return a.value}return""};
cvox.DomUtil.getText=function(a,b){var c=cvox.DomUtil.getTitle(a),d=cvox.DomUtil.getValue(a);c.length==0&&(c=cvox.DomUtil.getLabel(a,!1));var e="";c&&d?e=d+" "+c:c?e=c:d&&(e=d);if(!cvox.DomUtil.isControl(a))for(c=0;c<a.childNodes.length;c++)if(d=a.childNodes[c],!b||!cvox.DomUtil.isControl(d)){var f=window.getComputedStyle(d,null);!cvox.DomUtil.isInvisibleStyle(f)&&!cvox.AriaUtil.isHidden(a)&&(e+=" "+cvox.DomUtil.getText(d))}return e=e.replace(/\s+/g," ").replace(/^\s+|\s+$/g,"")};
cvox.DomUtil.getImageTitle=function(a){a.hasAttribute("alt")?a=a.alt:a.hasAttribute("title")?a=a.title:(a=a.src,a.substring(0,4)!="data"?(a=a.substring(a.lastIndexOf("/")+1,a.lastIndexOf(".")),a=a.length>=1&&a.length<=16?a+" Image":"Image"):a="Image");return a};
cvox.DomUtil.hasContent=function(a){if(a.nodeType==8)return!1;if(cvox.DomUtil.isDescendantOf(a,"HEAD"))return!1;if(cvox.DomUtil.isDescendantOf(a,"SCRIPT"))return!1;if(cvox.DomUtil.isDescendantOf(a,"NOSCRIPT"))return!1;if(cvox.DomUtil.isDescendantOf(a,"STYLE"))return!1;for(var b=a;b&&b.nodeType==3;)b=b.parentNode;if(b){var c=document.defaultView.getComputedStyle(b,null);if(cvox.DomUtil.isInvisibleStyle(c))return!1;for(;b&&b.tagName!="BODY";){c=document.defaultView.getComputedStyle(b,null);if(cvox.DomUtil.isInvisibleStyle(c))return!1;
b=b.parentNode}}if(cvox.AriaUtil.isHidden(a))return!1;if(cvox.DomUtil.isControl(a))return!0;if(a.tagName=="IFRAME")return!0;for(b=a.parentElement;b&&b.tagName!="LABEL";)b=b.parentElement;if(b)if(c=b.querySelector("button,input,select,textarea"),b.hasAttribute("for")){if(b=b.getAttribute("for"),(b=document.getElementById(b))&&cvox.DomUtil.isControl(b)&&!c)return!1}else if(c)return!1;a=cvox.DomUtil.getText(a);if(a==="")return!1;return!0};
cvox.DomUtil.getAncestors=function(a){for(var b=[];a;)b.push(a),a=a.parentNode;for(b.reverse();b.length&&!b[0].tagName&&!b[0].nodeValue;)b.shift();return b};cvox.DomUtil.compareAncestors=function(a,b){for(var c=0;a[c]&&b[c]&&a[c]==b[c];)c++;!a[c]&&!b[c]&&(c=-1);return c};cvox.DomUtil.getUniqueAncestors=function(a,b){var c=cvox.DomUtil.getAncestors(a),d=cvox.DomUtil.getAncestors(b),c=cvox.DomUtil.compareAncestors(c,d);return d.slice(c)};
cvox.DomUtil.getBasicNodeInformation=function(a){var b=cvox.DomUtil.getBasicNodeRole(a);b.length>0&&(b=b+" "+cvox.DomUtil.getBasicNodeState(a));return b};cvox.DomUtil.getBasicNodeRole=function(a){var b;(b=cvox.AriaUtil.getRoleName(a))||(b=a.tagName=="INPUT"?cvox.DomUtil.INPUT_TYPE_TO_INFORMATION_TABLE[a.type]:cvox.DomUtil.TAG_TO_INFORMATION_TABLE[a.tagName]);b||(b="");return b};
cvox.DomUtil.getBasicNodeState=function(a){var b;(b=cvox.AriaUtil.getState(a))?b+=" ":b="";if(a.tagName=="INPUT"){if(a.type=="checkbox"||a.type=="radio")b+=a.checked?" checked":" not checked"}else a.tagName=="SELECT"&&(b=b+" "+(a.selectedIndex+1)+" of "+a.options.length);return b};cvox.DomUtil.getInformationFromAncestors=function(a){for(var b="",c=0,d;d=a[c];c++)d=cvox.DomUtil.getBasicNodeInformation(d),d.length>0&&(b=b+" "+d);return b};
cvox.DomUtil.isFocusable=function(a){if(!a||typeof a.tabIndex!="number")return!1;if(a.tabIndex>=0)return!0;if(a.hasAttribute&&a.hasAttribute("tabindex")&&a.getAttribute("tabindex")=="-1")return!0;return!1};
cvox.DomUtil.setFocus=function(a){var b=window.getSelection(),c;b.rangeCount>0&&(c=b.getRangeAt(0));for(document.activeElement&&!cvox.DomUtil.isDescendantOfNode(a,document.activeElement)&&document.activeElement.blur();a&&!cvox.DomUtil.isFocusable(a);)a=a.parentNode;cvox.DomUtil.isFocusable(a)?a.focus():document.activeElement&&document.activeElement.tagName!="BODY"&&document.activeElement.blur();cvox.DomUtil.isInputTypeText(a)?a.select():c&&(b.removeAllRanges(),b.addRange(c))};
cvox.DomUtil.isAttachedToDocument=function(a){for(;a;){if(a.tagName&&a.tagName=="HTML")return!0;a=a.parentNode}return!1};
cvox.DomUtil.clickElem=function(a,b){var c=document.createEvent("MouseEvents");c.initMouseEvent("mousedown",!0,!0,document.defaultView,1,0,0,0,0,!1,!1,b,!1,0,null);try{a.dispatchEvent(c)}catch(d){}c=document.createEvent("MouseEvents");c.initMouseEvent("mouseup",!0,!0,document.defaultView,1,0,0,0,0,!1,!1,b,!1,0,null);try{a.dispatchEvent(c)}catch(e){}c=document.createEvent("MouseEvents");c.initMouseEvent("click",!0,!0,document.defaultView,1,0,0,0,0,!1,!1,b,!1,0,null);try{a.dispatchEvent(c)}catch(f){}c=
a.hasAttribute?a.getAttribute("href"):"";if(a.tagName=="A"&&c&&c!="#")b?window.open(a.href):document.location=a.href};cvox.DomUtil.isInputTypeText=function(a){if(!a||a.constructor!=HTMLInputElement)return!1;switch(a.type){case "email":case "number":case "password":case "search":case "text":case "tel":case "url":case "":return!0;default:return!1}};
cvox.DomUtil.isControl=function(a){if(cvox.AriaUtil.isControlWidget(a))return!0;if(a.tagName)switch(a.tagName){case "BUTTON":case "TEXTAREA":case "SELECT":return!0;case "INPUT":return a.type!="hidden"}if(a.isContentEditable)return!0;return!1};cvox.DomUtil.nextLeafNode=function(a){for(;a&&!a.nextSibling;)a=a.parentNode;if(a&&a.nextSibling)for(a=a.nextSibling;!cvox.DomUtil.isLeafNode(a);)a=a.firstChild;return a};
cvox.DomUtil.previousLeafNode=function(a){for(;a&&!a.previousSibling;)a=a.parentNode;if(a&&a.previousSibling)for(a=a.previousSibling;!cvox.DomUtil.isLeafNode(a);)a=a.lastChild;return a};cvox.DomUtil.getControlValueAndStateString=function(a,b){var c=cvox.DomUtil.getValue(a),d=cvox.DomUtil.getBasicNodeState(a);if(!b)return c+" "+d;var e=cvox.DomUtil.getTitle(a),f=cvox.DomUtil.getLabel(a,!1);e.length<1&&f.length<1&&(f=cvox.DomUtil.getLabel(a,!0));return f+" "+e+" "+c+" "+d};cvox.IFrameInfo=function(a,b){this.element=a;this.height=b};cvox.BaseModifier=function(){this.annotations=null;this.listenerInstalled=!1;this.iframes={};this.iframeCount=0;this.height=-1;this.lastProcessTime=null;this.minimumReprocessDelay=0;this.reprocessTimerSet=!1;this.addCrossFrameMessageListener()};cvox.BaseModifier.IFRAME_HEIGHT="IFrame Height";cvox.BaseModifier.prototype.enable=function(){this.processStyleSheets(!0)};
cvox.BaseModifier.prototype.processStyleSheets=function(a){for(var b=[],c=!1,d=0;d<document.styleSheets.length;d++){var e=document.styleSheets[d];if(!e.disabled){if(e.ownerNode.hasAttribute("chromeshades")){var f=parseInt(e.ownerNode.getAttribute("chromeshades"),10);if(f==e.cssRules.length)continue}c=!0;e.cssRules?(f=this.fixModifiableStyleSheet(e),e.ownerNode.setAttribute("chromeshades",""+f)):e.href&&b.push(e.href)}}if(c||a)b.length>0?(a={command:"stylesheet_request",firstTime:a,hrefs:b},cvox.ExtensionBridge.send(a)):
this.finishStyleSheetPrep(a)};cvox.BaseModifier.prototype.fixModifiableStyleSheet=function(a){for(var b=a.cssRules.length,c=0;c<b;c++){var d=a.cssRules[c];if(d&&d.style){var e=d.style.getPropertyValue("visibility"),f=d.style.getPropertyPriority("visibility"),e=e&&f?"visibility:"+e+" !"+f+";":e?"visibility:"+e+";":"",f=d.style.getPropertyValue("display"),g=d.style.getPropertyPriority("display"),f=f&&g?"display:"+f+" !"+g+";":f?"display:"+f+";":"";d.style.cssText=e+f}}return b};
cvox.BaseModifier.prototype.finishStyleSheetPrep=function(a){for(var b=0;b<document.styleSheets.length;b++){var c=document.styleSheets[b];if(!c.ownerNode.hasAttribute("chromeshades"))c.disabled=!0}if(a){document.body.setAttribute("chromeshades_show","1");try{this.processDOM()}catch(d){}try{this.finishProcessingAfterProcessDOM()}catch(e){}this.lastProcessTime=new Date;this.minimumReprocessDelay=1E3;document.body.setAttribute("chromeshades_show","2");window.setInterval(goog.bind(this.onIdle,this),5E3)}};
cvox.BaseModifier.prototype.forAllNodes=function(a,b){for(var c=a.firstChild;c&&c!=a;){if(c!=this.annotations&&c.id!="screen"){var d=window.getComputedStyle(c,null);b(c,d);if(c.firstChild){c=c.firstChild;continue}}for(;!c.nextSibling&&c!=a;)c=c.parentNode;if(c!=a)c=c.nextSibling}};
cvox.BaseModifier.prototype.reprocess=function(){if(this.minimumReprocessDelay!=0){var a=new Date,b=this.minimumReprocessDelay-(a-this.lastProcessTime);if(b>0){if(!this.reprocessTimerSet)this.reprocessTimerSet=!0,window.setTimeout(goog.bind(this.reprocess,this),b)}else{this.minimumReprocessDelay=0;this.removeSubtreeModifiedListener();try{this.processStyleSheets(!1)}catch(c){}try{this.processDOM()}catch(d){}try{this.finishProcessingAfterProcessDOM()}catch(e){}b=new Date;a=b-a;this.lastProcessTime=
b;this.minimumReprocessDelay=1E3+a*2;this.reprocessTimerSet=!1}}};cvox.BaseModifier.prototype.onIdle=function(){this.reprocess();for(var a=0;a<this.iframeCount;a++){var b=this.iframes[a];b&&b.element&&b.element.parentElement&&window.getComputedStyle(b.element,null).display!="none"&&cvox.Interframe.sendIdToIFrame(a,b.element)}};
cvox.BaseModifier.prototype.addCrossFrameMessageListener=function(){cvox.Interframe.addListener(goog.bind(function(a){if(a.command==cvox.BaseModifier.IFRAME_HEIGHT){var b=a.sourceId,b=this.iframes[b],a=parseInt(a.height,10);if(b&&a!=b.height)b.height=a,b.element.style.height=20+b.height+"px",window.setTimeout(goog.bind(function(){this.reprocess()},this),0)}else a.command==cvox.Interframe.SET_ID&&this.sendHeightToParent()},this))};
cvox.BaseModifier.prototype.processDOM=function(a){if(!a)a=document.body;for(var b=2,c=[0],d=1;d<=6;d++)c.push(b),a.querySelector("H"+d)&&(b+=2);var b=0,e=[],f={};f.node=a;f.indent=0;this.forAllNodes(a,goog.bind(function(a,d){if(!(a.style&&a.style.display=="none")&&!(d&&d.display=="none"&&a.constructor!=HTMLBRElement))if(a.constructor==HTMLImageElement&&a.hasAttribute("alt")&&a.alt=="")a.style.cssText="width: 0px !important; height: 0px !important; overflow: hidden !important;";else{for(a.constructor==
HTMLHeadingElement&&(b=c[a.tagName[1]-0-1]);!cvox.DomUtil.isDescendantOfNode(a,f.node);)f=e.pop();var i=0;if(b!=f.indent)i=b-f.indent,e.push(f),f={},f.node=a,f.indent=b;a.constructor==HTMLHeadingElement&&(b=c[a.tagName[1]-0]);var i=this.processNode(a,d,i),o=null;if(a.constructor==HTMLIFrameElement){for(var p=this.iframeCount,n=0;n<this.iframeCount;n++)this.iframes[n].element==a&&(o=this.iframes[n],p=n);p==this.iframeCount&&(this.iframeCount++,this.iframes[p]=new cvox.IFrameInfo(a,-1));cvox.Interframe.sendIdToIFrame(p,
a);i+=o&&o.height>0?" height: "+(20+o.height)+"px !important;":" height: 0px !important; border: 0px !important;";i+=" overflow: hidden; display: block;";a.setAttribute("scrolling","no")}if(a.constructor==HTMLImageElement&&(a.hasAttribute("width")&&a.removeAttribute("width"),a.hasAttribute("height")&&a.removeAttribute("height"),a.hasAttribute("alt")&&a.alt.length>0)){if(a.alt.length>30)a.alt=a.alt.substr(0,30);i+=" width: "+a.alt.length+"em !important;"}if(a.style)a.style.cssText=i}},this));!this.annotations||
!this.annotations.parentElement?(this.annotations=document.createElement("div"),this.annotations.id="chromeshades_annotations",document.body.appendChild(this.annotations)):this.annotations.nextSibling!=null&&(document.body.removeChild(this.annotations),document.body.appendChild(this.annotations))};
cvox.BaseModifier.prototype.processNode=function(a,b){var c="";b&&(c="display: "+b.display+";");var d="";a.style&&(d=a.getAttribute("role"));if(b&&b.visibility=="hidden"||d=="presentation")c+=" width: 0px !important; height: 0px !important; overflow: hidden !important;";a.style&&a.style.visibility&&(c+=" visibility: "+a.style.visibility+";");if(a.constructor==HTMLButtonElement||a.constructor==HTMLAnchorElement&&a.href||d=="button"||d=="link")if(a.hasAttribute("aria-label"))a.innerText=a.getAttribute("aria-label");
else if(a.hasAttribute("aria-labelledby")){if(d=a.getAttribute("aria-labelledby"),d=document.getElementById(d))a.innerText=cvox.DomUtil.getText(d)}else if(a.hasAttribute("title"))a.innerText=a.getAttribute("title");a.constructor==HTMLTableCellElement&&(a.removeAttribute("width"),a.removeAttribute("bgcolor"));a.constructor==HTMLTableRowElement&&a.removeAttribute("bgcolor");if(a.constructor==HTMLTableElement)a.removeAttribute("width"),a.removeAttribute("cellpadding"),a.removeAttribute("cellspacing"),
a.removeAttribute("bgcolor"),a.border="0";return c};cvox.BaseModifier.prototype.sendHeightToParent=function(){window.top==window||cvox.Interframe.id===void 0||this.height==-1||cvox.Interframe.sendMessageToParentWindow({command:cvox.BaseModifier.IFRAME_HEIGHT,height:this.height})};
cvox.BaseModifier.prototype.finishProcessingAfterProcessDOM=function(){var a=document.createElement("div");document.body.appendChild(a);window.setTimeout(goog.bind(function(){a.parentElement?(this.height=a.offsetTop,document.body.removeChild(a)):this.height=document.body.lastChild?document.body.lastChild.offsetTop+document.body.lastChild.offsetHeight:0;this.sendHeightToParent()},this),0);window.setTimeout(goog.bind(this.addSubtreeModifiedListener,this),1E3)};
cvox.BaseModifier.prototype.addSubtreeModifiedListener=function(){if(!this.subtreeModifiedListener)this.subtreeModifiedListener=goog.bind(this.onSubtreeModified,this);if(!this.listenerInstalled)document.addEventListener("DOMSubtreeModified",this.subtreeModifiedListener,!0),this.listenerInstalled=!0};
cvox.BaseModifier.prototype.removeSubtreeModifiedListener=function(){if(this.listenerInstalled)document.removeEventListener("DOMSubtreeModified",this.subtreeModifiedListener,!0),this.listenerInstalled=!1};cvox.BaseModifier.prototype.onSubtreeModified=function(){this.removeSubtreeModifiedListener();window.setTimeout(goog.bind(function(){this.reprocess()},this),100)};cvox.ShadesModifier=function(){cvox.BaseModifier.call(this);this.forceBlock=!1};goog.inherits(cvox.ShadesModifier,cvox.BaseModifier);
cvox.ShadesModifier.prototype.isControl=function(a){var b="";a.style&&(b=a.getAttribute("role"));if(a.constructor==HTMLButtonElement||a.constructor==HTMLSelectElement||a.constructor==HTMLAnchorElement&&a.href||a.constructor==HTMLInputElement&&a.type!="hidden"||b=="alert"||b=="alertdialog"||b=="button"||b=="checkbox"||b=="dialog"||b=="gridcell"||b=="link"||b=="log"||b=="marquee"||b=="menuitem"||b=="menuitemcheckbox"||b=="menuitemradio"||b=="option"||b=="progressbar"||b=="radio"||b=="scrollbar"||b==
"slider"||b=="spinbutton"||b=="status"||b=="tab"||b=="tabpanel"||b=="textbox"||b=="timer"||b=="tooltip"||b=="treeitem")return!0;return!1};cvox.ShadesModifier.prototype.isLeafNode=function(a){if(cvox.DomUtil.isLeafNode(a))return!0;if(this.isControl(a))return!0;return!1};cvox.ShadesModifier.prototype.processDOM=function(a){document.compatMode=="BackCompat"&&this.applyQuirksModeHacks();this.forceBlock=!1;cvox.BaseModifier.prototype.processDOM.call(this,a)};
cvox.ShadesModifier.prototype.processNode=function(a,b,c){var d=cvox.BaseModifier.prototype.processNode.call(this,a,b,c);if(a.constructor==HTMLBRElement)d+=" display: none !important;",this.forceBlock=!0;this.forceBlock&&(d+=" display:block;");this.forceBlock=!1;a.style&&a.removeAttribute("align");b&&b.display=="inline-block"&&(d+=" display:block;");if(a.constructor==HTMLInputElement&&!a.hasAttribute("placeholder")){var e=cvox.DomUtil.getLabel(a,!1);e&&a.setAttribute("placeholder",e)}if(a.constructor==
HTMLAnchorElement&&a.href||a.style&&a.getAttribute("role")=="link"){for(var e=!0,f=a,b=b.display;b!="block"&&f!=document.body;){if(f.previousSibling){e=!1;break}var f=f.parentNode,g=window.getComputedStyle(f,null);if(g)b=g.display}e||a.setAttribute("forceNewline"," ")}d+=a.constructor==HTMLIFrameElement?" width: 40em !important;":" max-width: 30em;";if(a.constructor==HTMLUListElement||a.constructor==HTMLOListElement||a.constructor==HTMLImageElement||a.constructor==HTMLIFrameElement||a.constructor==
HTMLTableCellElement||a.constructor==HTMLTableRowElement||this.isLeafNode(a)&&cvox.DomUtil.getText(a))d+=" display:block;";a.constructor==HTMLLIElement&&(d+=" display:list-item;");c!=0&&(d+=" margin-left: "+c+"em !important;");return d};
cvox.ShadesModifier.prototype.applyQuirksModeHacks=function(){for(var a=document.getElementsByTagName("TABLE"),b=0;b<a.length;b++)for(var c=a[b],c=cvox.XpathUtil.evalXPath("child::tbody/tr",c),d=0;d<c.length;d++)for(var e=c[d],f=cvox.XpathUtil.evalXPath("child::td | child::th",e),g=1;g<f.length;g++){var j=f[g],i=document.createElement("TR");e.nextSibling?e.parentElement.insertBefore(i,e.nextSibling):e.parentElement.appendChild(i);i.appendChild(j);e=i}};cvox.ChromeShades=function(){};cvox.ChromeShades.processSubtree=function(a){cvox.ChromeShades.modifier=new cvox.ShadesModifier;cvox.ChromeShades.modifier.processDOM(a)};
